### ISSUE TITLE
Set up auto-deploy on create tag

### ISSUE THREAD

**Issue by tolu** [oxyc/grunt-lint-inline#13]
@oxyc what do you think about setting up deployment from travis on creating new tags?
As far as I can see it looks as easy as adding

```
deploy:
  provider: npm
  api_key: "YOUR API KEY"
  on:
    tags: true
```

to the .travis.yml
http://docs.travis-ci.com/user/deployment/npm/
